# Generated by Django 3.1.7 on 2021-02-28 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_auto_20210228_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
