# Generated by Django 3.1.7 on 2021-03-05 08:06

import datetime
from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0006_auto_20210304_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='date',
            field=models.DateField(default=datetime.date(2021, 3, 5)),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=2,
                                      default=Decimal('0.00'),
                                      max_digits=9,
                                      validators=[django.core.validators.MinValueValidator
                                                  (Decimal('0.00'))]),
        ),
    ]
