# Generated by Django 3.1.7 on 2021-03-06 18:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0008_auto_20210305_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='date',
            field=models.DateField(default=datetime.date(2021, 3, 6)),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
