# Generated by Django 3.1.7 on 2021-03-09 14:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0012_auto_20210307_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='operation',
            name='date',
            field=models.DateField(default=datetime.date(2021, 3, 9)),
        ),
    ]
